// SPDX-License-Identifier: MIT

//! Numerical interoperability states from T.82 (03/1993), Table 24.
//! See docs/provenance.md for the adoption decision and source scope.

use super::QmState;

/// Standard probability states, ordered by the normative state index.
pub const STANDARD_STATES: [QmState; 113] = [
    QmState {
        qe: 0x5a1d,
        next_lps: 1,
        next_mps: 1,
        switch_mps: true,
    },
    QmState {
        qe: 0x2586,
        next_lps: 14,
        next_mps: 2,
        switch_mps: false,
    },
    QmState {
        qe: 0x1114,
        next_lps: 16,
        next_mps: 3,
        switch_mps: false,
    },
    QmState {
        qe: 0x080b,
        next_lps: 18,
        next_mps: 4,
        switch_mps: false,
    },
    QmState {
        qe: 0x03d8,
        next_lps: 20,
        next_mps: 5,
        switch_mps: false,
    },
    QmState {
        qe: 0x01da,
        next_lps: 23,
        next_mps: 6,
        switch_mps: false,
    },
    QmState {
        qe: 0x00e5,
        next_lps: 25,
        next_mps: 7,
        switch_mps: false,
    },
    QmState {
        qe: 0x006f,
        next_lps: 28,
        next_mps: 8,
        switch_mps: false,
    },
    QmState {
        qe: 0x0036,
        next_lps: 30,
        next_mps: 9,
        switch_mps: false,
    },
    QmState {
        qe: 0x001a,
        next_lps: 33,
        next_mps: 10,
        switch_mps: false,
    },
    QmState {
        qe: 0x000d,
        next_lps: 35,
        next_mps: 11,
        switch_mps: false,
    },
    QmState {
        qe: 0x0006,
        next_lps: 9,
        next_mps: 12,
        switch_mps: false,
    },
    QmState {
        qe: 0x0003,
        next_lps: 10,
        next_mps: 13,
        switch_mps: false,
    },
    QmState {
        qe: 0x0001,
        next_lps: 12,
        next_mps: 13,
        switch_mps: false,
    },
    QmState {
        qe: 0x5a7f,
        next_lps: 15,
        next_mps: 15,
        switch_mps: true,
    },
    QmState {
        qe: 0x3f25,
        next_lps: 36,
        next_mps: 16,
        switch_mps: false,
    },
    QmState {
        qe: 0x2cf2,
        next_lps: 38,
        next_mps: 17,
        switch_mps: false,
    },
    QmState {
        qe: 0x207c,
        next_lps: 39,
        next_mps: 18,
        switch_mps: false,
    },
    QmState {
        qe: 0x17b9,
        next_lps: 40,
        next_mps: 19,
        switch_mps: false,
    },
    QmState {
        qe: 0x1182,
        next_lps: 42,
        next_mps: 20,
        switch_mps: false,
    },
    QmState {
        qe: 0x0cef,
        next_lps: 43,
        next_mps: 21,
        switch_mps: false,
    },
    QmState {
        qe: 0x09a1,
        next_lps: 45,
        next_mps: 22,
        switch_mps: false,
    },
    QmState {
        qe: 0x072f,
        next_lps: 46,
        next_mps: 23,
        switch_mps: false,
    },
    QmState {
        qe: 0x055c,
        next_lps: 48,
        next_mps: 24,
        switch_mps: false,
    },
    QmState {
        qe: 0x0406,
        next_lps: 49,
        next_mps: 25,
        switch_mps: false,
    },
    QmState {
        qe: 0x0303,
        next_lps: 51,
        next_mps: 26,
        switch_mps: false,
    },
    QmState {
        qe: 0x0240,
        next_lps: 52,
        next_mps: 27,
        switch_mps: false,
    },
    QmState {
        qe: 0x01b1,
        next_lps: 54,
        next_mps: 28,
        switch_mps: false,
    },
    QmState {
        qe: 0x0144,
        next_lps: 56,
        next_mps: 29,
        switch_mps: false,
    },
    QmState {
        qe: 0x00f5,
        next_lps: 57,
        next_mps: 30,
        switch_mps: false,
    },
    QmState {
        qe: 0x00b7,
        next_lps: 59,
        next_mps: 31,
        switch_mps: false,
    },
    QmState {
        qe: 0x008a,
        next_lps: 60,
        next_mps: 32,
        switch_mps: false,
    },
    QmState {
        qe: 0x0068,
        next_lps: 62,
        next_mps: 33,
        switch_mps: false,
    },
    QmState {
        qe: 0x004e,
        next_lps: 63,
        next_mps: 34,
        switch_mps: false,
    },
    QmState {
        qe: 0x003b,
        next_lps: 32,
        next_mps: 35,
        switch_mps: false,
    },
    QmState {
        qe: 0x002c,
        next_lps: 33,
        next_mps: 9,
        switch_mps: false,
    },
    QmState {
        qe: 0x5ae1,
        next_lps: 37,
        next_mps: 37,
        switch_mps: true,
    },
    QmState {
        qe: 0x484c,
        next_lps: 64,
        next_mps: 38,
        switch_mps: false,
    },
    QmState {
        qe: 0x3a0d,
        next_lps: 65,
        next_mps: 39,
        switch_mps: false,
    },
    QmState {
        qe: 0x2ef1,
        next_lps: 67,
        next_mps: 40,
        switch_mps: false,
    },
    QmState {
        qe: 0x261f,
        next_lps: 68,
        next_mps: 41,
        switch_mps: false,
    },
    QmState {
        qe: 0x1f33,
        next_lps: 69,
        next_mps: 42,
        switch_mps: false,
    },
    QmState {
        qe: 0x19a8,
        next_lps: 70,
        next_mps: 43,
        switch_mps: false,
    },
    QmState {
        qe: 0x1518,
        next_lps: 72,
        next_mps: 44,
        switch_mps: false,
    },
    QmState {
        qe: 0x1177,
        next_lps: 73,
        next_mps: 45,
        switch_mps: false,
    },
    QmState {
        qe: 0x0e74,
        next_lps: 74,
        next_mps: 46,
        switch_mps: false,
    },
    QmState {
        qe: 0x0bfb,
        next_lps: 75,
        next_mps: 47,
        switch_mps: false,
    },
    QmState {
        qe: 0x09f8,
        next_lps: 77,
        next_mps: 48,
        switch_mps: false,
    },
    QmState {
        qe: 0x0861,
        next_lps: 78,
        next_mps: 49,
        switch_mps: false,
    },
    QmState {
        qe: 0x0706,
        next_lps: 79,
        next_mps: 50,
        switch_mps: false,
    },
    QmState {
        qe: 0x05cd,
        next_lps: 48,
        next_mps: 51,
        switch_mps: false,
    },
    QmState {
        qe: 0x04de,
        next_lps: 50,
        next_mps: 52,
        switch_mps: false,
    },
    QmState {
        qe: 0x040f,
        next_lps: 50,
        next_mps: 53,
        switch_mps: false,
    },
    QmState {
        qe: 0x0363,
        next_lps: 51,
        next_mps: 54,
        switch_mps: false,
    },
    QmState {
        qe: 0x02d4,
        next_lps: 52,
        next_mps: 55,
        switch_mps: false,
    },
    QmState {
        qe: 0x025c,
        next_lps: 53,
        next_mps: 56,
        switch_mps: false,
    },
    QmState {
        qe: 0x01f8,
        next_lps: 54,
        next_mps: 57,
        switch_mps: false,
    },
    QmState {
        qe: 0x01a4,
        next_lps: 55,
        next_mps: 58,
        switch_mps: false,
    },
    QmState {
        qe: 0x0160,
        next_lps: 56,
        next_mps: 59,
        switch_mps: false,
    },
    QmState {
        qe: 0x0125,
        next_lps: 57,
        next_mps: 60,
        switch_mps: false,
    },
    QmState {
        qe: 0x00f6,
        next_lps: 58,
        next_mps: 61,
        switch_mps: false,
    },
    QmState {
        qe: 0x00cb,
        next_lps: 59,
        next_mps: 62,
        switch_mps: false,
    },
    QmState {
        qe: 0x00ab,
        next_lps: 61,
        next_mps: 63,
        switch_mps: false,
    },
    QmState {
        qe: 0x008f,
        next_lps: 61,
        next_mps: 32,
        switch_mps: false,
    },
    QmState {
        qe: 0x5b12,
        next_lps: 65,
        next_mps: 65,
        switch_mps: true,
    },
    QmState {
        qe: 0x4d04,
        next_lps: 80,
        next_mps: 66,
        switch_mps: false,
    },
    QmState {
        qe: 0x412c,
        next_lps: 81,
        next_mps: 67,
        switch_mps: false,
    },
    QmState {
        qe: 0x37d8,
        next_lps: 82,
        next_mps: 68,
        switch_mps: false,
    },
    QmState {
        qe: 0x2fe8,
        next_lps: 83,
        next_mps: 69,
        switch_mps: false,
    },
    QmState {
        qe: 0x293c,
        next_lps: 84,
        next_mps: 70,
        switch_mps: false,
    },
    QmState {
        qe: 0x2379,
        next_lps: 86,
        next_mps: 71,
        switch_mps: false,
    },
    QmState {
        qe: 0x1edf,
        next_lps: 87,
        next_mps: 72,
        switch_mps: false,
    },
    QmState {
        qe: 0x1aa9,
        next_lps: 87,
        next_mps: 73,
        switch_mps: false,
    },
    QmState {
        qe: 0x174e,
        next_lps: 72,
        next_mps: 74,
        switch_mps: false,
    },
    QmState {
        qe: 0x1424,
        next_lps: 72,
        next_mps: 75,
        switch_mps: false,
    },
    QmState {
        qe: 0x119c,
        next_lps: 74,
        next_mps: 76,
        switch_mps: false,
    },
    QmState {
        qe: 0x0f6b,
        next_lps: 74,
        next_mps: 77,
        switch_mps: false,
    },
    QmState {
        qe: 0x0d51,
        next_lps: 75,
        next_mps: 78,
        switch_mps: false,
    },
    QmState {
        qe: 0x0bb6,
        next_lps: 77,
        next_mps: 79,
        switch_mps: false,
    },
    QmState {
        qe: 0x0a40,
        next_lps: 77,
        next_mps: 48,
        switch_mps: false,
    },
    QmState {
        qe: 0x5832,
        next_lps: 80,
        next_mps: 81,
        switch_mps: true,
    },
    QmState {
        qe: 0x4d1c,
        next_lps: 88,
        next_mps: 82,
        switch_mps: false,
    },
    QmState {
        qe: 0x438e,
        next_lps: 89,
        next_mps: 83,
        switch_mps: false,
    },
    QmState {
        qe: 0x3bdd,
        next_lps: 90,
        next_mps: 84,
        switch_mps: false,
    },
    QmState {
        qe: 0x34ee,
        next_lps: 91,
        next_mps: 85,
        switch_mps: false,
    },
    QmState {
        qe: 0x2eae,
        next_lps: 92,
        next_mps: 86,
        switch_mps: false,
    },
    QmState {
        qe: 0x299a,
        next_lps: 93,
        next_mps: 87,
        switch_mps: false,
    },
    QmState {
        qe: 0x2516,
        next_lps: 86,
        next_mps: 71,
        switch_mps: false,
    },
    QmState {
        qe: 0x5570,
        next_lps: 88,
        next_mps: 89,
        switch_mps: true,
    },
    QmState {
        qe: 0x4ca9,
        next_lps: 95,
        next_mps: 90,
        switch_mps: false,
    },
    QmState {
        qe: 0x44d9,
        next_lps: 96,
        next_mps: 91,
        switch_mps: false,
    },
    QmState {
        qe: 0x3e22,
        next_lps: 97,
        next_mps: 92,
        switch_mps: false,
    },
    QmState {
        qe: 0x3824,
        next_lps: 99,
        next_mps: 93,
        switch_mps: false,
    },
    QmState {
        qe: 0x32b4,
        next_lps: 99,
        next_mps: 94,
        switch_mps: false,
    },
    QmState {
        qe: 0x2e17,
        next_lps: 93,
        next_mps: 86,
        switch_mps: false,
    },
    QmState {
        qe: 0x56a8,
        next_lps: 95,
        next_mps: 96,
        switch_mps: true,
    },
    QmState {
        qe: 0x4f46,
        next_lps: 101,
        next_mps: 97,
        switch_mps: false,
    },
    QmState {
        qe: 0x47e5,
        next_lps: 102,
        next_mps: 98,
        switch_mps: false,
    },
    QmState {
        qe: 0x41cf,
        next_lps: 103,
        next_mps: 99,
        switch_mps: false,
    },
    QmState {
        qe: 0x3c3d,
        next_lps: 104,
        next_mps: 100,
        switch_mps: false,
    },
    QmState {
        qe: 0x375e,
        next_lps: 99,
        next_mps: 93,
        switch_mps: false,
    },
    QmState {
        qe: 0x5231,
        next_lps: 105,
        next_mps: 102,
        switch_mps: false,
    },
    QmState {
        qe: 0x4c0f,
        next_lps: 106,
        next_mps: 103,
        switch_mps: false,
    },
    QmState {
        qe: 0x4639,
        next_lps: 107,
        next_mps: 104,
        switch_mps: false,
    },
    QmState {
        qe: 0x415e,
        next_lps: 103,
        next_mps: 99,
        switch_mps: false,
    },
    QmState {
        qe: 0x5627,
        next_lps: 105,
        next_mps: 106,
        switch_mps: true,
    },
    QmState {
        qe: 0x50e7,
        next_lps: 108,
        next_mps: 107,
        switch_mps: false,
    },
    QmState {
        qe: 0x4b85,
        next_lps: 109,
        next_mps: 103,
        switch_mps: false,
    },
    QmState {
        qe: 0x5597,
        next_lps: 110,
        next_mps: 109,
        switch_mps: false,
    },
    QmState {
        qe: 0x504f,
        next_lps: 111,
        next_mps: 107,
        switch_mps: false,
    },
    QmState {
        qe: 0x5a10,
        next_lps: 110,
        next_mps: 111,
        switch_mps: true,
    },
    QmState {
        qe: 0x5522,
        next_lps: 112,
        next_mps: 109,
        switch_mps: false,
    },
    QmState {
        qe: 0x59eb,
        next_lps: 112,
        next_mps: 111,
        switch_mps: true,
    },
];
