[package]
name = "caj2pdf-cli"
version = "0.4.0"
edition = "2024"
rust-version = "1.88.0"
license = "MIT"
description = "Native command-line interface for caj2pdf"
repository = "https://github.com/rwv/caj2pdf-rust"
publish = ["crates-io"]
readme = "../../README.md"
include = ["src/**", "Cargo.toml", "README.md", "LICENSE"]

[[bin]]
name = "caj2pdf"
path = "src/main.rs"

[dependencies]
caj2pdf-core = { version = "0.4.0", path = "../caj2pdf-core" }

[target.'cfg(unix)'.dependencies]
signal-hook = { version = "0.4", default-features = false }

[target."cfg(windows)".dependencies]
ctrlc = "3.5.2"
winapi-util = "0.1.11"
